### ISSUE TITLE
GUI error and blocked - Traccar 3.10

### ISSUE THREAD

**Issue by DanSkytrack** [tananaev/traccar-web#465] opened 2017-04-04 12:24 UTC
Scenario:
Admin makes an user  with User Limit =2  (non zero) ; the other fields in permission section not checked.
Admin assigns to this user some vehicles .
Admin make a group and assigns to this group the same (or some) vehicles. Also assigns this group  to the user just created.

**First case.**
The user just  created signs in ; then goes to menu in  users and see that group assigned by the admin.
If he tries to uncheck  that group assigned by administrator then the error bellow occurs and the only way to get rid of it is to close the browser window.
![image](https://cloud.githubusercontent.com/assets/26308874/24656262/7de3e1ac-194a-11e7-8b18-a999ec937794.png)
**Second case**
The user signs in ; then goes to menu in  users and see the vehicles assigned for him by the admin.
If he tries to uncheck  any of those vehicles assigned by administrator then the error bellow occurs and the only way to get rid of it is to close the browser window.
![image](https://cloud.githubusercontent.com/assets/26308874/24656291/93ab4336-194a-11e7-8cfc-1135a9ea6f04.png)

**Comment by Abyss777** [comment] 2017-04-04 12:56
Hello,

First screenshot is about unchecking Devices not Groups, there should not be any limits in unlinking Groups from himself for Manager. Please provide the error if it really is.

Second behavior is expected https://www.traccar.org/documentation-user-management/

Anyway, thanks for feedback, there was an issue about interface hanging, it will be fixed.

**Comment by DanSkytrack** [comment] 2017-04-04 13:01
Hi,
Yes, I have uploaded the same error, sorry.
Now I am attaching the correct one ( for the first case, unchecking groups).
Thanks.
![gr err](https://cloud.githubusercontent.com/assets/26308874/24657680/d835d6ce-194f-11e7-8079-7ff8b54310d9.jpg)

**Comment by Abyss777** [comment] 2017-04-04 13:47
I'm still can't reproduce the problem. Did you try to restart the server?

**Comment by DanSkytrack** [comment] 2017-04-04 15:19
Hi,
The problem shows up only if you uncheck that group and without closing the window check it back again.
I have restarted the server and the error appears again.
Thanks.

**Comment by Abyss777** [comment] 2017-04-04 16:00
It is rather logical behavior. If you unlinked Group from yourself - you lost access to Group. You can't link it back because you already do not have access to it.

Probably it is not very obvious in UI... @tananaev  May be we should update UI behavior? IMHO It's not worth it.

**Closed** 2017-04-04 21:51 UTC

**Comment by tananaev** [comment] 2017-04-04 21:53
Merged the fix.
